import { ProductionStage, DivisionType, UserRole } from './types';

export interface DeadlineTemplate {
  id: string;
  title: string;
  description: string;
  daysFromNow: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  targetType: 'SEMUA' | 'DIVISI' | 'PERAN';
  targetDivision?: DivisionType;
  targetRole?: UserRole;
  isCritical: boolean;
  reference: string;
  deadlineRef: string;
}

// =========================================================
// TEMPLATE DEADLINE BERDASARKAN DOKUMEN REVISI PENILAIAN 360°
// Sesuai Bagian 6: Tugas Bertenggat per Peran per Tahap
// =========================================================
export const DEADLINE_TEMPLATES: Record<ProductionStage, DeadlineTemplate[]> = {

  // ============================================
  // TAHAP 1: PERSIAPAN (Bobot 20%)
  // ============================================
  PERSIAPAN: [
    // ---------- PIMPINAN PRODUKSI ----------
    {
      id: 'persiapan-pimpro-1',
      title: '★ Master Timeline Produksi',
      description: 'Menyusun Master Timeline di platform web dengan pengesahan Guru Pembimbing. Menetapkan jadwal larangan aktivitas fisik pada pekan ujian PAS/SAS dan libur semester.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-pimpro-2',
      title: '★ Penetapan Koordinator & Pembagian Tugas',
      description: 'Menetapkan koordinator tiap divisi dan membagi tanggung jawab sesuai struktur kepanitiaan.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-pimpro-3',
      title: 'Rapat Pleno Perdana',
      description: 'Memimpin Rapat Pleno perdana dengan seluruh panitia. Memperkenalkan struktur, timeline, dan pembagian divisi.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-pimpro-4',
      title: '★ Perizinan Lokasi & Keramaian',
      description: 'Mengurus perizinan lokasi pementasan dan izin keramaian ke pihak sekolah/berwenang.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- SEKRETARIS ----------
    {
      id: 'persiapan-sekre-1',
      title: '★ Surat Izin & Proposal Produksi',
      description: 'Menyusun surat izin dan proposal produksi teater untuk diajukan ke pihak sekolah.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: true,
      reference: 'Job Desc Sekretaris § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-sekre-2',
      title: '★ Jadwal Master di Menu Jadwal & Agenda',
      description: 'Mengunggah jadwal master seluruh kegiatan ke menu Jadwal & Agenda.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: true,
      reference: 'Job Desc Sekretaris § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-sekre-3',
      title: 'Arsip Naskah Drama',
      description: 'Mengunggah dan mengarsipkan naskah drama ke menu Dokumen & Arsip.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pra-Produksi',
      deadlineRef: 'Tengah Persiapan',
    },
    {
      id: 'persiapan-sekre-4',
      title: 'Notulen Rapat Pleno Perdana',
      description: 'Membuat notulen Rapat Pleno perdana, unggah H+1 rapat.',
      daysFromNow: 6,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pra-Produksi',
      deadlineRef: 'H+1 rapat',
    },

    // ---------- BENDAHARA ----------
    {
      id: 'persiapan-bend-1',
      title: 'Aktivasi Kas & Periode Pertama',
      description: 'Mengaktifkan fitur kas di menu Kas & Buku Kas, menetapkan nominal dan periode pertama.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-bend-2',
      title: '★ RAB Final Bertanda Tangan',
      description: 'Menyusun RAB lengkap via menu RAB Digital, ekspor ke Word, meminta tanda tangan Pimpro, dan mengunggah RAB Final yang sudah ditandatangani ke sistem.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: true,
      reference: 'Job Desc Bendahara § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- SUTRADARA ----------
    {
      id: 'persiapan-sut-1',
      title: '★ Konsep Penyutradaraan',
      description: 'Menyusun dan mengunggah Konsep Penyutradaraan (visi artistik, tema, gaya pementasan) ke platform web.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },
    {
      id: 'persiapan-sut-2',
      title: 'Rapat Artistik Perdana',
      description: 'Memimpin rapat artistik perdana dengan Koor Tata Panggung, Busana, Rias, dan Musik.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pra-Produksi',
      deadlineRef: 'Tengah Persiapan',
    },
    {
      id: 'persiapan-sut-3',
      title: '★ Audisi & Pengumuman Casting',
      description: 'Menyelenggarakan audisi pemain dan mengumumkan hasil casting di platform web.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pra-Produksi',
      deadlineRef: 'Tengah Persiapan',
    },
    {
      id: 'persiapan-sut-4',
      title: 'Jadwal Latihan Awal',
      description: 'Menyusun jadwal latihan awal untuk seluruh pemain dan mempublikasikannya.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- ASISTEN SUTRADARA ----------
    {
      id: 'persiapan-astrada-1',
      title: 'Jadwal Latihan (Call Sheet)',
      description: 'Menyusun jadwal latihan per adegan dalam bentuk Call Sheet.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },
    {
      id: 'persiapan-astrada-2',
      title: '★ Penyiapan Prompt Book',
      description: 'Menyusun dan mengunggah Prompt Book lengkap dengan Cue Sheet audio & lighting ke menu Studio.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: true,
      reference: 'Job Desc Astrada § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- PEMERAN ----------
    {
      id: 'persiapan-pemeran-1',
      title: 'Audisi & Cold Reading',
      description: 'Mengikuti audisi dan sesi cold reading untuk menentukan peran.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pra-Produksi',
      deadlineRef: 'Sesuai jadwal audisi',
    },
    {
      id: 'persiapan-pemeran-2',
      title: '★ Analisis Karakter',
      description: 'Menyusun lembar analisis karakter tokoh yang diperankan dan mengunggahnya ke platform web.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: true,
      reference: 'Job Desc Pemeran § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },
    {
      id: 'persiapan-pemeran-3',
      title: 'Table Reading Awal',
      description: 'Mengikuti table reading awal bersama seluruh pemeran dan sutradara.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- KOORDINATOR (Tugas Tambahan) ----------
    {
      id: 'persiapan-koor-all-1',
      title: 'Jadwal Divisi di Menu Jadwal Divisi',
      description: 'Menyusun jadwal internal divisi dan mempublikasikannya di menu Jadwal Divisi.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'SEMUA',
      isCritical: false,
      reference: 'Job Desc Koordinator § Pra-Produksi',
      deadlineRef: 'Awal Persiapan',
    },

    // ---------- DIVISI PERLENGKAPAN ----------
    {
      id: 'persiapan-koor-perlengkapan-1',
      title: '★ Daftar Properti per Adegan',
      description: 'Menyusun daftar breakdown properti per adegan (prioritas daur ulang) dan mengunggahnya ke menu Properti.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: true,
      reference: 'Job Desc Perlengkapan § Pra-Produksi',
      deadlineRef: 'Tengah Persiapan',
    },

    // ---------- DIVISI PUBLIKASI & DOKUMENTASI ----------
    {
      id: 'persiapan-koor-publikasi-1',
      title: '★ Rancangan Kalender Konten',
      description: 'Menyusun kalender konten publikasi (H-30 sampai Hari-H) dan mengunggahnya ke menu Jadwal Konten.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: true,
      reference: 'Job Desc Publikasi § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- DIVISI TATA PANGGUNG ----------
    {
      id: 'persiapan-koor-panggung-1',
      title: '★ Denah Panggung & Sketsa Konsep',
      description: 'Merancang denah panggung 2D per adegan dan sketsa konsep tata cahaya. Unggah ke platform web.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: true,
      reference: 'Job Desc Tata Panggung § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- DIVISI TATA RIAS ----------
    {
      id: 'persiapan-koor-rias-1',
      title: 'Moodboard Rias',
      description: 'Menyusun moodboard rias berbasis analisis karakter dan mengunggahnya ke menu Face Chart.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: false,
      reference: 'Job Desc Tata Rias § Pra-Produksi',
      deadlineRef: 'Tengah Persiapan',
    },
    {
      id: 'persiapan-koor-rias-2',
      title: '★ Face Chart Seluruh Pemeran',
      description: 'Membuat face chart lengkap untuk seluruh pemeran (Korektif/Karakter/Fantasi).',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: true,
      reference: 'Job Desc Tata Rias § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- DIVISI TATA BUSANA ----------
    {
      id: 'persiapan-koor-busana-1',
      title: '★ Costume Chart & Swatch (Desain Disetujui)',
      description: 'Menyusun costume chart & swatch kain untuk seluruh pemeran. Desain harus disetujui sebelum tahap POTONG pada Pelaksanaan.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: true,
      reference: 'Job Desc Tata Busana § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },

    // ---------- DIVISI TATA MUSIK ----------
    {
      id: 'persiapan-koor-musik-1',
      title: 'Cue Sheet Awal',
      description: 'Menyusun draft awal Cue Sheet audio untuk seluruh adegan. Unggah ke menu Cue Sheet.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: false,
      reference: 'Job Desc Tata Musik § Pra-Produksi',
      deadlineRef: 'Akhir Persiapan',
    },
  ],

  // ============================================
  // TAHAP 2: PELAKSANAAN (Bobot 35%)
  // ============================================
  PELAKSANAAN: [
    // ---------- PIMPINAN PRODUKSI ----------
    {
      id: 'pelaksanaan-pimpro-1',
      title: 'Rapat Pleno Berkala',
      description: 'Memimpin Rapat Pleno berkala untuk memonitor progres seluruh divisi.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pelaksanaan',
      deadlineRef: 'Per sesi',
    },
    {
      id: 'pelaksanaan-pimpro-2',
      title: 'Pemantauan Progres Divisi',
      description: 'Melakukan pemantauan progres mingguan setiap divisi melalui dashboard web.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-pimpro-3',
      title: '★ Laporan Progres ke Guru',
      description: 'Mengirim laporan progres mingguan kepada Guru Pembimbing via web.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-pimpro-4',
      title: 'Tindak Lanjut Hambatan Lintas Divisi',
      description: 'Menindaklanjuti hambatan lintas divisi maksimal 2 hari kerja setelah dilaporkan.',
      daysFromNow: 2,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pelaksanaan',
      deadlineRef: 'Maks 2 hari kerja setelah dilaporkan',
    },

    // ---------- SEKRETARIS ----------
    {
      id: 'pelaksanaan-sekre-1',
      title: '★ Notulen Tiap Rapat Pleno',
      description: 'Membuat notulen setiap Rapat Pleno, unggah H+1 setelah rapat.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: true,
      reference: 'Job Desc Sekretaris § Pelaksanaan',
      deadlineRef: 'H+1 rapat',
    },
    {
      id: 'pelaksanaan-sekre-2',
      title: 'Membuka Sesi Presensi',
      description: 'Membuka sesi presensi sebelum kegiatan mulai di menu Presensi.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pelaksanaan',
      deadlineRef: 'Sebelum kegiatan mulai',
    },
    {
      id: 'pelaksanaan-sekre-3',
      title: 'Broadcast Jadwal Kegiatan',
      description: 'Mengirim broadcast jadwal kegiatan ke semua siswa H-1 sebelum kegiatan.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pelaksanaan',
      deadlineRef: 'H-1 kegiatan',
    },
    {
      id: 'pelaksanaan-sekre-4',
      title: 'Arsip Dokumen Mingguan',
      description: 'Mengarsipkan semua dokumen produksi mingguan ke menu Dokumen & Arsip.',
      daysFromNow: 7,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },

    // ---------- BENDAHARA ----------
    {
      id: 'pelaksanaan-bend-1',
      title: 'Pengelolaan Periode Kas & Reminder',
      description: 'Mengelola periode kas di menu Kas, centang pembayaran, dan kirim reminder santun ke yang belum bayar.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pelaksanaan',
      deadlineRef: 'Tiap periode kas',
    },
    {
      id: 'pelaksanaan-bend-2',
      title: 'Pencatatan Buku Kas',
      description: 'Mencatat pemasukan & pengeluaran di Buku Kas pada hari yang sama dengan transaksi.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pelaksanaan',
      deadlineRef: 'Hari yang sama dengan transaksi',
    },
    {
      id: 'pelaksanaan-bend-3',
      title: 'Bukti Nota Diunggah',
      description: 'Mengunggah bukti nota ke Dokumen & Arsip maksimal 3 hari setelah transaksi.',
      daysFromNow: 3,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pelaksanaan',
      deadlineRef: 'Maks 3 hari setelah transaksi',
    },
    {
      id: 'pelaksanaan-bend-4',
      title: '★ Pembayaran Pengadaan Sesuai RAB',
      description: 'Membayar pengadaan sesuai RAB SEBELUM divisi yang membutuhkan mulai bekerja.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: true,
      reference: 'Job Desc Bendahara § Pelaksanaan',
      deadlineRef: 'Sebelum tugas divisi yang membutuhkannya',
    },

    // ---------- SUTRADARA ----------
    {
      id: 'pelaksanaan-sut-1',
      title: 'Latihan Rutin (Reading, Hafalan, Blocking)',
      description: 'Memimpin latihan rutin dengan fokus reading, hafalan, dan blocking.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pelaksanaan',
      deadlineRef: 'Per sesi',
    },
    {
      id: 'pelaksanaan-sut-2',
      title: 'Membuka Sesi Presensi Pemeran',
      description: 'Membuka sesi presensi untuk Pemeran & Tata Musik sebelum latihan dimulai.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pelaksanaan',
      deadlineRef: 'Sebelum latihan mulai',
    },
    {
      id: 'pelaksanaan-sut-3',
      title: 'Rapat Artistik Berkala',
      description: 'Memimpin rapat artistik berkala dengan Koor Tata Panggung, Busana, Rias, dan Musik.',
      daysFromNow: 7,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pelaksanaan',
      deadlineRef: 'Sesuai Jadwal & Agenda',
    },
    {
      id: 'pelaksanaan-sut-4',
      title: '★ Blocking Final',
      description: 'Menetapkan dan mengunci blocking final seluruh adegan SEBELUM Run-Through.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pelaksanaan',
      deadlineRef: 'Sebelum Run-Through',
    },

    // ---------- ASISTEN SUTRADARA ----------
    {
      id: 'pelaksanaan-astrada-1',
      title: '★ Prompt Book Diperbarui',
      description: 'Memperbarui Prompt Book setelah setiap sesi blocking, unggah H+1.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: true,
      reference: 'Job Desc Astrada § Pelaksanaan',
      deadlineRef: 'H+1 setiap sesi blocking',
    },
    {
      id: 'pelaksanaan-astrada-2',
      title: 'Catatan Latihan',
      description: 'Membuat catatan latihan harian untuk setiap sesi, unggah H+1.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pelaksanaan',
      deadlineRef: 'H+1 setiap sesi',
    },
    {
      id: 'pelaksanaan-astrada-3',
      title: 'Komunikasi Jadwal ke Pemeran',
      description: 'Mengirim reminder jadwal latihan ke pemeran H-1 sebelum sesi.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pelaksanaan',
      deadlineRef: 'H-1 sesi',
    },

    // ---------- PEMERAN ----------
    {
      id: 'pelaksanaan-pemeran-1',
      title: 'Latihan Rutin',
      description: 'Mengikuti latihan rutin reading, hafalan, dan blocking.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pelaksanaan',
      deadlineRef: 'Per sesi',
    },
    {
      id: 'pelaksanaan-pemeran-2',
      title: '★ Uji Hafalan Tiap Babak',
      description: 'Menyelesaikan uji hafalan tiap babak sesuai tenggat yang ditetapkan. Hafal tanpa membaca naskah.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: true,
      reference: 'Job Desc Pemeran § Pelaksanaan',
      deadlineRef: 'Sesuai tenggat uji per babak',
    },
    {
      id: 'pelaksanaan-pemeran-3',
      title: 'Penguasaan Blocking',
      description: 'Menguasai seluruh blocking SEBELUM Run-Through. Ingat tanpa diingatkan.',
      daysFromNow: 30,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pelaksanaan',
      deadlineRef: 'Sebelum Run-Through',
    },
    {
      id: 'pelaksanaan-pemeran-4',
      title: 'Fitting & Rias',
      description: 'Mengikuti sesi fitting kostum & uji rias sesuai jadwal yang ditetapkan.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pelaksanaan',
      deadlineRef: 'Sesuai jadwal',
    },

    // ---------- KOORDINATOR (Tugas Tambahan) ----------
    {
      id: 'pelaksanaan-koor-all-1',
      title: '★ Laporan Progres Mingguan ke Atasan',
      description: 'Melaporkan progres divisi mingguan ke Pimpro (atau Sutradara untuk divisi artistik) beserta persentase tugas divisi tepat waktu.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'SEMUA',
      isCritical: true,
      reference: 'Job Desc Koordinator § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },

    // ---------- PERLENGKAPAN ----------
    {
      id: 'pelaksanaan-perlengkapan-1',
      title: 'Pengadaan & Fabrikasi Properti',
      description: 'Mengerjakan pengadaan/fabrikasi properti. Update status properti (BELUM, PROSES, SELESAI) di menu Properti setiap minggu.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: false,
      reference: 'Job Desc Perlengkapan § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-perlengkapan-2',
      title: 'Uji Fungsi & Keamanan Properti',
      description: 'Melakukan uji fungsi & keamanan properti sebelum Run-Through.',
      daysFromNow: 30,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: false,
      reference: 'Job Desc Perlengkapan § Pelaksanaan',
      deadlineRef: 'Sebelum Run-Through',
    },
    {
      id: 'pelaksanaan-perlengkapan-3',
      title: '★ Properti Utama SELESAI',
      description: 'Semua properti utama harus berstatus SELESAI di menu Properti.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: true,
      reference: 'Job Desc Perlengkapan § Pelaksanaan',
      deadlineRef: 'Sebelum Run-Through',
    },

    // ---------- PUBLIKASI ----------
    {
      id: 'pelaksanaan-publikasi-1',
      title: '★ Poster Utama Rilis',
      description: 'Merilis poster utama pementasan di media sosial & mading sekolah.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: true,
      reference: 'Job Desc Publikasi § Pelaksanaan',
      deadlineRef: 'H-30 pementasan',
    },
    {
      id: 'pelaksanaan-publikasi-2',
      title: 'Teaser',
      description: 'Merilis video teaser pementasan.',
      daysFromNow: 21,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: false,
      reference: 'Job Desc Publikasi § Pelaksanaan',
      deadlineRef: 'H-14 pementasan',
    },
    {
      id: 'pelaksanaan-publikasi-3',
      title: '★ Tiket Dibuka',
      description: 'Membuka penjualan/pemesanan tiket pementasan sesuai jadwal yang ditetapkan Pimpro.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: true,
      reference: 'Job Desc Publikasi § Pelaksanaan',
      deadlineRef: 'Sesuai jadwal yang ditetapkan Pimpro',
    },
    {
      id: 'pelaksanaan-publikasi-4',
      title: 'Dokumentasi Latihan & Produksi',
      description: 'Mendokumentasikan latihan dan proses produksi (foto/video BTS) mingguan.',
      daysFromNow: 7,
      priority: 'MEDIUM',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: false,
      reference: 'Job Desc Publikasi § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },

    // ---------- TATA PANGGUNG ----------
    {
      id: 'pelaksanaan-panggung-1',
      title: 'Konstruksi Set',
      description: 'Mengerjakan konstruksi set panggung. Update status di menu Properti.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: false,
      reference: 'Job Desc Tata Panggung § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-panggung-2',
      title: 'Rancangan & Pemasangan Lampu',
      description: 'Merancang dan memasang tata cahaya (lampu, titik fokus) di panggung.',
      daysFromNow: 30,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: false,
      reference: 'Job Desc Tata Panggung § Pelaksanaan',
      deadlineRef: 'Akhir Pelaksanaan',
    },

    // ---------- TATA RIAS ----------
    {
      id: 'pelaksanaan-rias-1',
      title: 'Tes Alergi',
      description: 'Melakukan tes alergi produk rias pada seluruh pemeran SEBELUM sesi Fitting & Rias.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: false,
      reference: 'Job Desc Tata Rias § Pelaksanaan',
      deadlineRef: 'Sebelum Fitting & Rias',
    },
    {
      id: 'pelaksanaan-rias-2',
      title: 'Persiapan Ruang & Alat Rias',
      description: 'Menyiapkan ruang rias dan alat rias lengkap SEBELUM sesi Fitting & Rias.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: false,
      reference: 'Job Desc Tata Rias § Pelaksanaan',
      deadlineRef: 'Sebelum Fitting & Rias',
    },
    {
      id: 'pelaksanaan-rias-3',
      title: '★ Uji Rias',
      description: 'Melakukan uji rias seluruh pemeran sesuai face chart.',
      daysFromNow: 21,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: true,
      reference: 'Job Desc Tata Rias § Pelaksanaan',
      deadlineRef: 'Sesuai jadwal Fitting & Rias',
    },

    // ---------- TATA BUSANA ----------
    {
      id: 'pelaksanaan-busana-1',
      title: 'Status Kostum POTONG & JAHIT',
      description: 'Memperbarui status kostum (POTONG, JAHIT) di menu Kostum setiap minggu.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: false,
      reference: 'Job Desc Tata Busana § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-busana-2',
      title: '★ Seluruh Kostum Melewati FITTING',
      description: 'Semua kostum harus melewati tahap FITTING di menu Kostum SEBELUM Gladi Resik.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: true,
      reference: 'Job Desc Tata Busana § Pelaksanaan',
      deadlineRef: 'Sebelum Gladi Resik',
    },

    // ---------- TATA MUSIK ----------
    {
      id: 'pelaksanaan-musik-1',
      title: 'Komposisi / Penyuntingan Audio',
      description: 'Mengerjakan komposisi atau penyuntingan audio untuk seluruh cue. Update di menu Cue Sheet.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: false,
      reference: 'Job Desc Tata Musik § Pelaksanaan',
      deadlineRef: 'Mingguan',
    },
    {
      id: 'pelaksanaan-musik-2',
      title: 'Sinkronisasi Musik dengan Blocking',
      description: 'Menyinkronkan musik dengan blocking SEBELUM Run-Through.',
      daysFromNow: 30,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: false,
      reference: 'Job Desc Tata Musik § Pelaksanaan',
      deadlineRef: 'Sebelum Run-Through',
    },
    {
      id: 'pelaksanaan-musik-3',
      title: '★ Cue Sheet Final',
      description: 'Menyelesaikan Cue Sheet final seluruh cue SEBELUM Technical Rehearsal.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: true,
      reference: 'Job Desc Tata Musik § Pelaksanaan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
  ],

  // ============================================
  // TAHAP 3: PERTUNJUKAN (Bobot 30%)
  // ============================================
  PERTUNJUKAN: [
    // ---------- PIMPINAN PRODUKSI ----------
    {
      id: 'pertunjukan-pimpro-1',
      title: '★ Keputusan Layak Lanjut Gladi Resik',
      description: 'Mengambil keputusan final apakah produksi layak lanjut ke Gladi Resik. Berdasarkan evaluasi Technical Rehearsal.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pertunjukan',
      deadlineRef: 'Sebelum Gladi Resik',
    },
    {
      id: 'pertunjukan-pimpro-2',
      title: 'Memimpin Technical Rehearsal & Gladi Resik',
      description: 'Memimpin langsung pelaksanaan Technical Rehearsal dan Gladi Resik.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pertunjukan',
      deadlineRef: 'Per sesi',
    },
    {
      id: 'pertunjukan-pimpro-3',
      title: 'Koordinasi Hari-H',
      description: 'Mengoordinasikan seluruh tim pada hari pementasan (taklimat 10 menit sebelum pintu dibuka).',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- SEKRETARIS ----------
    {
      id: 'pertunjukan-sekre-1',
      title: 'Presensi Gladi Resik & Pementasan',
      description: 'Membuka sesi presensi untuk Gladi Resik dan Pementasan sebelum kegiatan mulai.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pertunjukan',
      deadlineRef: 'Sebelum kegiatan mulai',
    },
    {
      id: 'pertunjukan-sekre-2',
      title: '★ Dokumen Perizinan Hari-H',
      description: 'Memastikan seluruh dokumen perizinan siap di hari-H (H-1 persiapan final).',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: true,
      reference: 'Job Desc Sekretaris § Pertunjukan',
      deadlineRef: 'H-1',
    },
    {
      id: 'pertunjukan-sekre-3',
      title: 'Komunikasi Undangan',
      description: 'Mengirim undangan ke tamu, orang tua, dan pihak sekolah H-7 sebelum pementasan.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pertunjukan',
      deadlineRef: 'H-7',
    },

    // ---------- BENDAHARA ----------
    {
      id: 'pertunjukan-bend-1',
      title: '★ Penyelesaian Pembayaran',
      description: 'Menyelesaikan seluruh pembayaran sebelum Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: true,
      reference: 'Job Desc Bendahara § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-bend-2',
      title: 'Pajak & Perizinan Berbiaya',
      description: 'Menyelesaikan pajak & perizinan berbiaya H-7 sebelum pementasan.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pertunjukan',
      deadlineRef: 'H-7',
    },
    {
      id: 'pertunjukan-bend-3',
      title: 'Pencatatan Kas Hari-H',
      description: 'Mencatat seluruh transaksi kas di hari-H pementasan.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- SUTRADARA ----------
    {
      id: 'pertunjukan-sut-1',
      title: '★ Run-Through Penuh',
      description: 'Memimpin Run-Through penuh seluruh adegan SEBELUM Technical Rehearsal.',
      daysFromNow: 4,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-sut-2',
      title: '★ Technical Rehearsal',
      description: 'Memimpin Technical Rehearsal dengan seluruh teknis (sound, lighting, properti) berjalan.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pertunjukan',
      deadlineRef: 'Sebelum Gladi Resik',
    },
    {
      id: 'pertunjukan-sut-3',
      title: '★ Gladi Resik',
      description: 'Memimpin Gladi Resik penuh dengan kostum, properti, dan tata panggung lengkap.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pertunjukan',
      deadlineRef: 'Sesuai Jadwal & Agenda',
    },
    {
      id: 'pertunjukan-sut-4',
      title: 'Pementasan',
      description: 'Memastikan pementasan berjalan sesuai visi artistik. Memantau durasi 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- ASISTEN SUTRADARA ----------
    {
      id: 'pertunjukan-astrada-1',
      title: 'Cue List Final',
      description: 'Menyelesaikan Cue List final (audio & lighting) SEBELUM Gladi Resik.',
      daysFromNow: 2,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pertunjukan',
      deadlineRef: 'Sebelum Gladi Resik',
    },
    {
      id: 'pertunjukan-astrada-2',
      title: '★ Standby Cue',
      description: 'Standby di area cue setiap sesi Gladi Resik & Pementasan untuk eksekusi cue tepat waktu.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: true,
      reference: 'Job Desc Astrada § Pertunjukan',
      deadlineRef: 'Per sesi Gladi dan Pementasan',
    },

    // ---------- PEMERAN ----------
    {
      id: 'pertunjukan-pemeran-1',
      title: '★ Run-Through',
      description: 'Mengikuti Run-Through penuh SEBELUM Technical Rehearsal. Hafal seluruh dialog tanpa naskah.',
      daysFromNow: 4,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: true,
      reference: 'Job Desc Pemeran § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-pemeran-2',
      title: '★ Gladi Resik',
      description: 'Mengikuti Gladi Resik dengan kostum & rias lengkap sesuai Jadwal & Agenda.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: true,
      reference: 'Job Desc Pemeran § Pertunjukan',
      deadlineRef: 'Sesuai Jadwal & Agenda',
    },
    {
      id: 'pertunjukan-pemeran-3',
      title: 'Pementasan',
      description: 'Tampil di pementasan utama. Jaga proyeksi suara, penjiwaan, dan interaksi panggung.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- PERLENGKAPAN ----------
    {
      id: 'pertunjukan-perlengkapan-1',
      title: '★ Seluruh Properti SELESAI',
      description: 'Semua properti berstatus SELESAI di menu Properti SEBELUM Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: true,
      reference: 'Job Desc Perlengkapan § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-perlengkapan-2',
      title: 'Latihan Pergantian Properti',
      description: 'Latihan pergantian properti cepat saat Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: false,
      reference: 'Job Desc Perlengkapan § Pertunjukan',
      deadlineRef: 'Saat Technical Rehearsal',
    },
    {
      id: 'pertunjukan-perlengkapan-3',
      title: 'Penataan Properti Hari-H',
      description: 'Menata properti di prop table wing panggung pada Hari-H.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: false,
      reference: 'Job Desc Perlengkapan § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- PUBLIKASI ----------
    {
      id: 'pertunjukan-publikasi-1',
      title: 'Konten Pengingat',
      description: 'Merilis konten pengingat pementasan H-7 & H-1.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: false,
      reference: 'Job Desc Publikasi § Pertunjukan',
      deadlineRef: 'H-7 dan H-1',
    },
    {
      id: 'pertunjukan-publikasi-2',
      title: '★ Liputan & Dokumentasi Hari-H',
      description: 'Meliput pementasan hari-H dengan kamera statis di angle terbaik + foto candid penonton.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: true,
      reference: 'Job Desc Publikasi § Pertunjukan',
      deadlineRef: 'Hari-H',
    },

    // ---------- TATA PANGGUNG ----------
    {
      id: 'pertunjukan-panggung-1',
      title: 'Uji Kekuatan & Keamanan Set',
      description: 'Menguji kekuatan & keamanan set panggung SEBELUM Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: false,
      reference: 'Job Desc Tata Panggung § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-panggung-2',
      title: '★ Set Siap Uji',
      description: 'Set panggung siap untuk diuji SEBELUM Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: true,
      reference: 'Job Desc Tata Panggung § Pertunjukan',
      deadlineRef: 'Sebelum Technical Rehearsal',
    },
    {
      id: 'pertunjukan-panggung-3',
      title: '★ Cue Lampu Terpasang',
      description: 'Semua cue lampu terpasang dan teruji SEBELUM Gladi Resik.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: true,
      reference: 'Job Desc Tata Panggung § Pertunjukan',
      deadlineRef: 'Sebelum Gladi Resik',
    },

    // ---------- TATA RIAS ----------
    {
      id: 'pertunjukan-rias-1',
      title: '★ Rias Seluruh Pemeran Siap',
      description: 'Rias seluruh pemeran siap sesuai jadwal Gladi Resik.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: true,
      reference: 'Job Desc Tata Rias § Pertunjukan',
      deadlineRef: 'Sesuai jadwal Gladi Resik',
    },
    {
      id: 'pertunjukan-rias-2',
      title: 'Touch-Up',
      description: 'Standby touch-up cepat di antara adegan pada setiap sesi.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: false,
      reference: 'Job Desc Tata Rias § Pertunjukan',
      deadlineRef: 'Per sesi',
    },

    // ---------- TATA BUSANA ----------
    {
      id: 'pertunjukan-busana-1',
      title: 'Uji Pergantian Cepat',
      description: 'Melatih uji pergantian cepat (quick change) pemain saat Technical Rehearsal.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: false,
      reference: 'Job Desc Tata Busana § Pertunjukan',
      deadlineRef: 'Saat Technical Rehearsal',
    },
    {
      id: 'pertunjukan-busana-2',
      title: 'Perawatan Kostum',
      description: 'Merawat kostum setiap sesi Gladi Resik & Pementasan.',
      daysFromNow: 1,
      priority: 'MEDIUM',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: false,
      reference: 'Job Desc Tata Busana § Pertunjukan',
      deadlineRef: 'Per sesi',
    },

    // ---------- TATA MUSIK ----------
    {
      id: 'pertunjukan-musik-1',
      title: '★ Uji Sistem Suara & Mikrofon',
      description: 'Menguji sistem suara dan mikrofon SEBELUM Gladi Resik.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: true,
      reference: 'Job Desc Tata Musik § Pertunjukan',
      deadlineRef: 'Sebelum Gladi Resik',
    },
    {
      id: 'pertunjukan-musik-2',
      title: 'Operasi Cue',
      description: 'Mengoperasikan seluruh cue audio selama setiap sesi (Gladi Resik & Pementasan).',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: false,
      reference: 'Job Desc Tata Musik § Pertunjukan',
      deadlineRef: 'Per sesi',
    },
  ],

  // ============================================
  // TAHAP 4: PASCA (Bobot 15%)
  // ============================================
  PASCA: [
    // ---------- PIMPINAN PRODUKSI ----------
    {
      id: 'pasca-pimpro-1',
      title: 'Rapat Evaluasi',
      description: 'Memimpin rapat evaluasi produksi bersama seluruh panitia di awal tahap Pasca.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pasca',
      deadlineRef: 'Awal Pasca',
    },
    {
      id: 'pasca-pimpro-2',
      title: '★ Laporan Akhir Produksi',
      description: 'Menyusun dan menyerahkan Laporan Akhir Produksi (LPJ komprehensif) ke Guru Pembimbing.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: true,
      reference: 'Job Desc Pimpro § Pasca',
      deadlineRef: 'Akhir Pasca',
    },
    {
      id: 'pasca-pimpro-3',
      title: 'Penyelesaian Pengembalian Fasilitas',
      description: 'Menyelesaikan pengembalian seluruh fasilitas sekolah yang dipinjam.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      isCritical: false,
      reference: 'Job Desc Pimpro § Pasca',
      deadlineRef: 'Awal Pasca',
    },

    // ---------- SEKRETARIS ----------
    {
      id: 'pasca-sekre-1',
      title: 'Arsip Dokumentasi',
      description: 'Mengarsipkan seluruh dokumentasi produksi ke menu Dokumen & Arsip.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pasca',
      deadlineRef: 'Tengah Pasca',
    },
    {
      id: 'pasca-sekre-2',
      title: 'Notulen Evaluasi',
      description: 'Membuat notulen rapat evaluasi produksi, unggah H+1 rapat.',
      daysFromNow: 4,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: false,
      reference: 'Job Desc Sekretaris § Pasca',
      deadlineRef: 'H+1 rapat',
    },
    {
      id: 'pasca-sekre-3',
      title: '★ Laporan Administrasi',
      description: 'Menyusun laporan administrasi akhir & distribusi sertifikat/surat apresiasi.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      isCritical: true,
      reference: 'Job Desc Sekretaris § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- BENDAHARA ----------
    {
      id: 'pasca-bend-1',
      title: 'Rekap Saldo Akhir',
      description: 'Merekap seluruh saldo akhir kas (siswa + pemasukan - pengeluaran) di awal Pasca.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pasca',
      deadlineRef: 'Awal Pasca',
    },
    {
      id: 'pasca-bend-2',
      title: 'Laporan Keuangan',
      description: 'Menyusun Laporan Keuangan (tabel Perbandingan Anggaran estimasi vs realisasi).',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: false,
      reference: 'Job Desc Bendahara § Pasca',
      deadlineRef: 'Tengah Pasca',
    },
    {
      id: 'pasca-bend-3',
      title: '★ LPJ Keuangan',
      description: 'Menyusun LPJ Keuangan akhir sebagai bagian LPJ Produksi.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      isCritical: true,
      reference: 'Job Desc Bendahara § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- SUTRADARA ----------
    {
      id: 'pasca-sut-1',
      title: 'Evaluasi Penyutradaraan',
      description: 'Menyusun evaluasi penyutradaraan di awal Pasca.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: false,
      reference: 'Job Desc Sutradara § Pasca',
      deadlineRef: 'Awal Pasca',
    },
    {
      id: 'pasca-sut-2',
      title: '★ Catatan Evaluasi Akhir',
      description: 'Menyusun catatan evaluasi akhir penyutradaraan + analisis perkembangan keaktoran individual.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      isCritical: true,
      reference: 'Job Desc Sutradara § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- ASISTEN SUTRADARA ----------
    {
      id: 'pasca-astrada-1',
      title: 'Catatan Evaluasi',
      description: 'Menyusun catatan evaluasi latihan di awal Pasca.',
      daysFromNow: 3,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pasca',
      deadlineRef: 'Awal Pasca',
    },
    {
      id: 'pasca-astrada-2',
      title: 'Arsip Prompt Book',
      description: 'Mengarsipkan Prompt Book final ke menu Dokumen & Arsip.',
      daysFromNow: 5,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      isCritical: false,
      reference: 'Job Desc Astrada § Pasca',
      deadlineRef: 'Tengah Pasca',
    },

    // ---------- PEMERAN ----------
    {
      id: 'pasca-pemeran-1',
      title: 'Refleksi Diri',
      description: 'Mengisi lembar refleksi diri keaktoran di platform web pada awal Pasca.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pasca',
      deadlineRef: 'Awal Pasca',
    },
    {
      id: 'pasca-pemeran-2',
      title: 'Evaluasi Akhir',
      description: 'Mengikuti sesi evaluasi akhir bersama Sutradara & Asisten.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemeran',
      isCritical: false,
      reference: 'Job Desc Pemeran § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- KOORDINATOR (Tugas Tambahan) ----------
    {
      id: 'pasca-koor-all-1',
      title: '★ Laporan Divisi',
      description: 'Menyusun laporan akhir divisi dan menyerahkannya ke atasan (Pimpro/Sutradara).',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'SEMUA',
      isCritical: true,
      reference: 'Job Desc Koordinator § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- PERLENGKAPAN ----------
    {
      id: 'pasca-perlengkapan-1',
      title: 'Inventaris & Pengembalian Properti',
      description: 'Mendata inventaris properti & mengembalikan ke tempat semula.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      isCritical: false,
      reference: 'Job Desc Perlengkapan § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- PUBLIKASI ----------
    {
      id: 'pasca-publikasi-1',
      title: 'Hasil Dokumentasi Pertunjukan',
      description: 'Menyunting aftermovie & mengunggah seluruh dokumentasi pertunjukan ke arsip digital.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      isCritical: false,
      reference: 'Job Desc Publikasi § Pasca',
      deadlineRef: 'Tengah Pasca',
    },

    // ---------- TATA PANGGUNG ----------
    {
      id: 'pasca-panggung-1',
      title: 'Strike & Pembongkaran Set',
      description: 'Membongkar set panggung & mengembalikan panggung ke kondisi semula pada awal Pasca.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      isCritical: false,
      reference: 'Job Desc Tata Panggung § Pasca',
      deadlineRef: 'Awal Pasca',
    },

    // ---------- TATA RIAS ----------
    {
      id: 'pasca-rias-1',
      title: 'Pembersihan & Inventaris Alat Rias',
      description: 'Membersihkan alat rias & mensterilkan untuk penyimpanan.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      isCritical: false,
      reference: 'Job Desc Tata Rias § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- TATA BUSANA ----------
    {
      id: 'pasca-busana-1',
      title: 'Inventaris & Pengembalian Kostum',
      description: 'Mencuci, merawat, dan mengembalikan seluruh kostum ke tempat penyimpanan.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      isCritical: false,
      reference: 'Job Desc Tata Busana § Pasca',
      deadlineRef: 'Akhir Pasca',
    },

    // ---------- TATA MUSIK ----------
    {
      id: 'pasca-musik-1',
      title: 'Arsip Audio',
      description: 'Mengarsipkan seluruh cue audio ke penyimpanan digital.',
      daysFromNow: 7,
      priority: 'MEDIUM',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      isCritical: false,
      reference: 'Job Desc Tata Musik § Pasca',
      deadlineRef: 'Akhir Pasca',
    },
  ],
};

// =========================================================
// INFO TAHAP
// =========================================================
export const STAGE_INFO: Record<ProductionStage, {
  label: string;
  color: string;
  gradient: string;
  desc: string;
}> = {
  PERSIAPAN: {
    label: 'Tahap 1 — Persiapan (20%)',
    color: 'amber',
    gradient: 'from-amber-600 to-amber-800',
    desc: 'Master Timeline, casting, RAB final, perizinan, sketsa & chart tiap divisi',
  },
  PELAKSANAAN: {
    label: 'Tahap 2 — Pelaksanaan (35%)',
    color: 'blue',
    gradient: 'from-blue-600 to-blue-800',
    desc: 'Blocking final, properti selesai, fitting kostum, cue sheet, set terkonstruksi',
  },
  PERTUNJUKAN: {
    label: 'Tahap 3 — Pertunjukan (30%)',
    color: 'purple',
    gradient: 'from-purple-600 to-purple-800',
    desc: 'Run-Through, Technical Rehearsal, Gladi Resik, Pementasan',
  },
  PASCA: {
    label: 'Tahap 4 — Pasca Produksi (15%)',
    color: 'emerald',
    gradient: 'from-emerald-600 to-emerald-800',
    desc: 'LPJ, laporan divisi, inventaris, evaluasi akhir',
  },
};
