import { ProductionStage, DivisionType, UserRole } from './types';

export interface DeadlineTemplate {
  id: string;
  title: string;
  description: string;
  daysFromNow: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  targetType: 'SEMUA' | 'DIVISI' | 'PERAN';
  targetDivision?: DivisionType;
  targetRole?: UserRole;
  reference: string; // acuan dari dokumen job desc
}

// =========================================================
// TEMPLATE PER TAHAP — DIKUTIP DARI DOKUMEN 12 PERAN RESMI
// =========================================================
export const DEADLINE_TEMPLATES: Record<ProductionStage, DeadlineTemplate[]> = {

  // ============================================
  // TAHAP 1: PERSIAPAN
  // ============================================
  PERSIAPAN: [
    {
      id: 'persiapan-1',
      title: 'Menyusun Master Production Schedule',
      description: 'Pimpinan Produksi menyusun Master Production Schedule di platform web dengan pengesahan Guru Pembimbing. Menetapkan pekan bebas ujian PAS/SAS dan libur semester dalam kalender kerja.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-2',
      title: 'Menyusun RAB & Kebijakan Material Daur Ulang',
      description: 'Bendahara menyusun Anggaran Pendapatan & Belanja via web, menetapkan kebijakan material daur ulang, dan mengatur sistem digitalisasi nota kas.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-3',
      title: 'Mengunggah Visi Penyutradaraan',
      description: 'Sutradara menyusun sistem latihan modular berbasis Scene Breakdown & mengunggah Visi Penyutradaraan ke web sebagai panduan kerja bersama.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-4',
      title: 'Menyusun Call Sheet & Upload Prompt Book',
      description: 'Asisten Sutradara menyusun Call Sheet latihan per adegan dan mengunggah naskah panduan utama prompt book berisi instruksi cueing.',
      daysFromNow: 8,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-5',
      title: 'Mendalami Karakter & Menyerahkan Jadwal Les',
      description: 'Pemain mendalami latar belakang tokoh, menyusun lembar analisis karakter di web, dan menyerahkan jadwal les pribadi melalui sistem web.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-6',
      title: 'Moodboard Kostum & Data Ukuran Tubuh Pemain',
      description: 'Divisi Kostum mengembangkan moodboard kostum (boleh pakai AI), upload rancangan visual ke web, dan mendata ukuran tubuh pemain dari data mandiri.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-7',
      title: 'Face Chart & Jadwal Urutan Rias',
      description: 'Divisi Rias membuat face chart berbasis analisis karakter (boleh pakai AI), upload ke web, dan menyusun jadwal urutan merias yang ringkas.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-8',
      title: 'Breakdown Properti & Denah Wing Panggung',
      description: 'Divisi Properti menyusun breakdown daftar properti per adegan (prioritas barang daur ulang) dan merancang denah penataan properti di wing panggung bersama Stage Crew.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-9',
      title: 'Sketsa Denah Panggung & Sistem Cross-Operator',
      description: 'Divisi Panggung merancang sketsa denah panggung 2D per adegan, upload ke web, dan menyusun sistem Cross-Operator (kru cadangan).',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-10',
      title: 'Strategi Publikasi & Kalender Konten',
      description: 'Divisi Dokpub menyusun strategi publikasi digital, merancang kalender konten, dan membuat materi promosi di waktu senggang.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Perencanaan Pra-Produksi',
    },
    {
      id: 'persiapan-11',
      title: 'Sound Cue Sheet & Tata Letak Mikrofon',
      description: 'Divisi Musik menginventarisasi alat musik, upload sound cue sheet ke web, merancang tata letak mikrofon panggung bersama Stage Crew, dan menerapkan sistem Cross-Operator.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Perencanaan Pra-Produksi',
    },
  ],

  // ============================================
  // TAHAP 2: PELAKSANAAN
  // ============================================
  PELAKSANAAN: [
    {
      id: 'pelaksanaan-1',
      title: 'Briefing & Latihan Rutin (Maks 2x/Minggu, Maks 1 Jam)',
      description: 'Seluruh divisi mengikuti pemanasan bersama, briefing singkat, dan latihan maks 1 jam. Total latihan maks 2x/minggu. Dilarang latihan di akhir pekan.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'SEMUA',
      reference: 'Job Desc Pimpro § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-2',
      title: 'Rekap Presensi Harian & Data Izin Les',
      description: 'Sekretaris mengelola rekapitulasi presensi harian dan data izin les akademik siswa di sistem web.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-3',
      title: 'Pengelolaan Arus Kas Harian via Web',
      description: 'Bendahara mengelola arus kas harian via web agar tidak menyita waktu belajar dan jadwal les.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-4',
      title: 'Setor Hafalan Dialog via Video Asinkron',
      description: 'Pemain menyetorkan latihan hafalan dialog via rekaman video ke platform web secara asinkron dari rumah tanpa mengganggu waktu belajar dan jam les.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-5',
      title: 'Setor Hafalan Dialog (Cek oleh Astrada)',
      description: 'Asisten Sutradara mengelola penyerahan setor hafalan dialog via rekaman audio/video singkat di web di luar pekan ujian dan libur semester.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-6',
      title: 'Fitting Kostum Bergantian & Simulasi Quick Change',
      description: 'Divisi Kostum melakukan fitting kostum bergantian (maks 1 jam/sesi termasuk rapat), memodifikasi pakaian bekas, dan melatih simulasi quick change.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-7',
      title: 'Latihan Aplikasi Rias pada Pemain & Shadow Player',
      description: 'Divisi Rias melatih aplikasi rias pada pemain dan Shadow Player (maks 1 jam/sesi termasuk briefing di sekolah).',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-8',
      title: 'Merakit Properti di Sekolah (Maks 1 Jam/Sesi)',
      description: 'Divisi Properti merakit properti sederhana di sekolah pada jam kegiatan resmi (maks 1 jam/pertemuan termasuk rapat teknis).',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-9',
      title: 'Pasang Lakban Spotting & Konstruksi Set',
      description: 'Divisi Panggung memasang lakban penanda spotting posisi pemain, konstruksi set panggung sederhana, dan simulasi pemindahan set (maks 1 jam/sesi).',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-10',
      title: 'Dokumentasi BTS & Upload Rekaman Latihan',
      description: 'Divisi Dokpub mendokumentasikan proses belakang layar, upload rekaman video latihan ke web agar Sutradara dan pemain dapat evaluasi asinkron dari rumah.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-11',
      title: 'Upload Draf Rekaman Musik Iringan',
      description: 'Divisi Musik mengunggah draf rekaman musik iringan ke web agar pemain bisa berlatih hafalan dari rumah secara mandiri.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Pelaksanaan Produksi',
    },
    {
      id: 'pelaksanaan-12',
      title: 'Henti Total Aktivitas Fisik (Pekan Ujian & Libur)',
      description: 'SEMUA divisi WAJIB menghentikan aktivitas fisik di sekolah selama 2 minggu pekan Ujian PAS/SAS dan 1 minggu libur semester. Aset dikunci & diamankan.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'SEMUA',
      reference: 'Job Desc Semua Peran § Pelaksanaan Produksi',
    },
  ],

  // ============================================
  // TAHAP 3: PERTUNJUKAN
  // ============================================
  PERTUNJUKAN: [
    {
      id: 'pertunjukan-1',
      title: 'Rapat Komando Akhir & Alokasi Waktu 45 Menit',
      description: 'Pimpro memimpin rapat komando akhir, koordinasi dengan pengelola tempat untuk alokasi 45 menit: 10 menit persiapan + 30 menit tampil + 5 menit pembongkaran set.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-2',
      title: 'Registrasi Tamu & Validasi Tiket Digital',
      description: 'Sekretaris berkoordinasi dengan tim registrasi untuk zonasi meja penerimaan tamu, validasi tiket digital, dan mencatat statistik kehadiran riil penonton.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-3',
      title: 'Penyediaan Dana Darurat P3K & Konsumsi Tim',
      description: 'Bendahara berkoordinasi dengan logistik untuk pembagian ruang penyimpanan, mengalokasikan dana darurat P3K & teknis cepat, dan berkoordinasi dengan Divisi Konsumsi.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-4',
      title: 'Gladi Bersih Utuh & Instruksi Alur Adegan',
      description: 'Sutradara memimpin gladi bersih utuh pada minggu pertama setelah masuk sekolah pasca-libur, berkoordinasi dengan Stage Manager agar durasi pertunjukan tepat 30 menit.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-5',
      title: 'Panggil Pemain dari Ruang Tunggu ke Wing',
      description: 'Asisten Sutradara berkoordinasi dengan Floor Manager untuk alur pemanggilan pemain, memandu pemanasan vokal singkat, dan mengontrol urutan adegan agar sesuai 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-6',
      title: 'Pemanasan Vokal Fisik & Standby di Wing',
      description: 'Semua pemain WAJIB mengikuti pemanasan vokal dan fisik singkat di balik panggung, menjaga ketenangan di ruang tunggu, dan siap di area wing tepat waktu.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-7',
      title: 'Penataan Area Ganti & Quick Change',
      description: 'Divisi Kostum berkoordinasi dengan penata busana kerabat kerja untuk pembagian area rak gantung, menata area ganti sesuai urutan adegan, dan mendampingi quick change pemain.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-8',
      title: 'Eksekusi Tata Rias & Touch-Up Cepat',
      description: 'Divisi Rias berkoordinasi dengan tim rias kerabat kerja untuk berbagi area cermin & listrik, eksekusi tata rias sesuai timeline, dan standby touch-up cepat di antara adegan.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-9',
      title: 'Penataan Prop Table & Transisi Properti Cepat',
      description: 'Divisi Properti berkoordinasi dengan tim logistik untuk pembagian zona prop table, menata properti dalam 10 menit persiapan, dan eksekusi transisi properti cepat selama 30 menit.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-10',
      title: 'Pasang Set 10 Menit & Bongkar Set 5 Menit',
      description: 'Divisi Panggung berkoordinasi dengan kru panggung kerabat kerja untuk eksekusi pasang set dalam 10 menit dan pembongkaran cepat dalam 5 menit terakhir. Jaga sterilitas area samping.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-11',
      title: 'Rekam Pementasan Utuh 30 Menit',
      description: 'Divisi Dokpub berkoordinasi untuk pembagian posisi tripod & sudut kamera, merekam pementasan utuh 30 menit dengan audio jernih, dan mengabadikan foto momen panggung.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Pertunjukan Show Time',
    },
    {
      id: 'pertunjukan-12',
      title: 'Check Sound 10 Menit & Musik Iringan Presisi',
      description: 'Divisi Musik berkoordinasi dengan sound engineer untuk pembagian channel mixer, check sound 10 menit persiapan awal, dan memainkan musik iringan presisi mengikuti alur adegan 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Pertunjukan Show Time',
    },
  ],

  // ============================================
  // TAHAP 4: PASCA PRODUKSI
  // ============================================
  PASCA: [
    {
      id: 'pasca-1',
      title: 'Pembersihan Total Panggung & Forum Apresiasi',
      description: 'Pimpro mengoordinasikan pembersihan total panggung, mengembalikan area ke pengelola tempat, memimpin forum apresiasi resmi, dan menyusun LPJ komprehensif berbasis web.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-2',
      title: 'Kompilasi Dokumen & Data Penonton ke Arsip Web',
      description: 'Sekretaris mengompilasi dokumen produksi, laporan presensi digital, dan data penonton ke dalam direktori arsip web yang terstruktur rapi.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-3',
      title: 'Rekapitulasi Nota & Laporan Keuangan Akhir',
      description: 'Bendahara merekapitulasi nota transaksi digital, menyusun Laporan Keuangan Akhir di web, menghitung sisa kas, dan memaparkan transparansi keuangan.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-4',
      title: 'Analisis Perkembangan Keaktoran Individual',
      description: 'Sutradara menyampaikan analisis perkembangan keaktoran harian secara individual via web dan mengonsolidasikan catatan akhir penyutradaraan.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-5',
      title: 'Konsolidasi Catatan Perkembangan Pemain',
      description: 'Asisten Sutradara mengonsolidasikan seluruh catatan perkembangan harian pemain dan mengunggahnya ke dalam arsip evaluasi web.',
      daysFromNow: 5,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-6',
      title: 'Refleksi Kritis Keaktoran & Bersihkan Rias',
      description: 'Pemain membersihkan riasan wajah, merapikan kostum pribadi, dan mengisi lembar refleksi kritis keaktoran di platform web.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-7',
      title: 'Cuci & Kembalikan Aset Kostum Pinjaman',
      description: 'Divisi Kostum melakukan pembersihan, pencucian, dan pengembalian seluruh aset kostum pinjaman serta menginput data inventaris akhir ke sistem web.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-8',
      title: 'Pembersihan Rias & Sterilkan Alat',
      description: 'Divisi Rias mendampingi pembersihan riasan pemain dengan make-up remover, mensterilkan kembali alat rias, dan mengunggah laporan kerja ke sistem web.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-9',
      title: 'Kembalikan Inventaris & Update Status Barang',
      description: 'Divisi Properti membersihkan area belakang panggung, mengembalikan inventaris sekolah, dan memperbarui status barang di sistem web.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-10',
      title: 'Bongkar Set & Kembalikan Panggung ke Semula',
      description: 'Divisi Panggung membongkar set dekorasi secara aman, mengembalikan kondisi panggung seperti semula, dan mengisi borang penilaian berjenjang di web.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-11',
      title: 'Sunting Aftermovie & Upload ke Repositori Web',
      description: 'Divisi Dokpub menyunting video aftermovie sinematik dan mengorganisir seluruh file foto & video ke repositori web yang dapat diakses semua siswa dan guru.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Evaluasi Pasca-Produksi',
    },
    {
      id: 'pasca-12',
      title: 'Rapikan Instrumen & Laporan Evaluasi Teknis Suara',
      description: 'Divisi Musik merapikan, membersihkan, dan mengembalikan seluruh instrumen musik ke tempat penyimpanan serta mengisi laporan evaluasi teknis suara di web.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Evaluasi Pasca-Produksi',
    },
  ],
};

// =========================================================
// INFO TAHAP — untuk UI
// =========================================================
export const STAGE_INFO: Record<ProductionStage, {
  label: string;
  color: string;
  gradient: string;
  desc: string;
}> = {
  PERSIAPAN: {
    label: 'Tahap 1 — Persiapan',
    color: 'amber',
    gradient: 'from-amber-600 to-amber-800',
    desc: 'Riset, naskah, casting, desain konsep, RAB, Master Schedule',
  },
  PELAKSANAAN: {
    label: 'Tahap 2 — Pelaksanaan',
    color: 'blue',
    gradient: 'from-blue-600 to-blue-800',
    desc: 'Latihan rutin, produksi properti & kostum, dokumentasi BTS',
  },
  PERTUNJUKAN: {
    label: 'Tahap 3 — Pertunjukan',
    color: 'purple',
    gradient: 'from-purple-600 to-purple-800',
    desc: 'Gladi bersih, pementasan utama, standby cue',
  },
  PASCA: {
    label: 'Tahap 4 — Pasca Produksi',
    color: 'emerald',
    gradient: 'from-emerald-600 to-emerald-800',
    desc: 'Evaluasi, LPJ, pengembalian aset, aftermovie',
  },
};
