import { ProductionStage, DivisionType, UserRole } from './types';

export interface TaskTemplate {
  id: string;
  title: string;
  description: string;
  daysFromNow: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  targetType: 'SEMUA' | 'DIVISI' | 'PERAN';
  targetDivision?: DivisionType;
  targetRole?: UserRole;
  reference: string;
}

// =====================================================
// BAGIAN 1: 6 PERAN UTAMA
// =====================================================

const PERSIAPAN: TaskTemplate[] = [
  { id: 'tp-persiapan-pimpro-1', title: 'Menyusun Master Production Schedule', description: 'Menyusun Master Production Schedule pada platform web dengan pengesahan resmi dari Guru Pembimbing dan Kepala Sekolah.', daysFromNow: 7, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Perencanaan' },
  { id: 'tp-persiapan-pimpro-2', title: 'Menetapkan Pekan Bebas Ujian & Libur', description: 'Menetapkan Pekan Bebas Ujian PAS/SAS (2 Minggu) dan Libur Semester (1 Minggu) dalam kalender kerja.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Perencanaan' },
  { id: 'tp-persiapan-pimpro-3', title: 'Batasi Latihan 2x/Minggu, 1 Jam, Tanpa Weekend', description: 'Membatasi latihan maks 2x/minggu sebelum H-14, durasi maks 1 jam/pertemuan, melarang kegiatan di akhir pekan.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Perencanaan' },
  { id: 'tp-persiapan-pimpro-4', title: 'Kontrol Target Divisi via Dashboard', description: 'Mengontrol ketercapaian target awal tiap divisi melalui dashboard web yang diakses real-time.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Perencanaan' },
  { id: 'tp-persiapan-sekre-1', title: 'Tata Kelola Administrasi Web', description: 'Mengelola administrasi berbasis web dan membuat formulir izin les/bimbel otomatis di sistem.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Perencanaan' },
  { id: 'tp-persiapan-sekre-2', title: 'Unggah Draf Naskah & Dokumen Kerja', description: 'Mengunggah draf naskah cetak dan dokumen kerja harian ke repositori web.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Perencanaan' },
  { id: 'tp-persiapan-bend-1', title: 'Menyusun RAB Produksi via Web', description: 'Menyusun Anggaran Pendapatan dan Belanja Produksi via web berdasarkan kesepakatan kelas.', daysFromNow: 10, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Perencanaan' },
  { id: 'tp-persiapan-bend-2', title: 'Kebijakan Material Daur Ulang', description: 'Menetapkan kebijakan pemanfaatan material daur ulang yang murah dan mudah didapat.', daysFromNow: 10, priority: 'MEDIUM', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Perencanaan' },
  { id: 'tp-persiapan-bend-3', title: 'Sistem Digitalisasi Nota & Kas', description: 'Mengatur sistem digitalisasi nota dan pembukuan kas yang real-time & diaudit Guru Pembimbing.', daysFromNow: 10, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Perencanaan' },
  { id: 'tp-persiapan-sut-1', title: 'Sistem Latihan Modular (Scene Breakdown)', description: 'Menyusun sistem latihan modular berbasis Scene Breakdown agar siswa hadir hanya saat adegannya dilatih.', daysFromNow: 7, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Perencanaan' },
  { id: 'tp-persiapan-sut-2', title: 'Unggah Visi Penyutradaraan', description: 'Mengunggah Visi Penyutradaraan ke platform web sebagai panduan kerja bersama.', daysFromNow: 7, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Perencanaan' },
  { id: 'tp-persiapan-astrada-1', title: 'Menyusun Call Sheet Per Adegan', description: 'Menyusun Call Sheet latihan per adegan dan menyelaraskan dengan jadwal les anggota.', daysFromNow: 8, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Perencanaan' },
  { id: 'tp-persiapan-astrada-2', title: 'Unggah Prompt Book & Cueing', description: 'Mengunggah naskah panduan utama prompt book berisi instruksi cueing ke web.', daysFromNow: 8, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Perencanaan' },
  { id: 'tp-persiapan-pemain-1', title: 'Mendalami Latar Belakang Tokoh', description: 'Mendalami latar belakang tokoh yang diperankan.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Perencanaan' },
  { id: 'tp-persiapan-pemain-2', title: 'Menyusun Lembar Analisis Karakter', description: 'Menyusun lembar analisis karakter di sistem web.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Perencanaan' },
  { id: 'tp-persiapan-pemain-3', title: 'Menyerahkan Jadwal Les Pribadi', description: 'Menyerahkan jadwal les pribadi melalui sistem web.', daysFromNow: 7, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Perencanaan' },
];

const PELAKSANAAN: TaskTemplate[] = [
  { id: 'tp-pelaksanaan-pimpro-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim di awal latihan.', daysFromNow: 14, priority: 'MEDIUM', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pimpro-2', title: 'Briefing Singkat & Latihan Tepat 60 Menit', description: 'Membuka latihan dengan briefing, memastikan seluruh rangkaian selesai tepat 60 menit, memantau izin les via web.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pimpro-3', title: 'Hentikan Aktivitas Fisik (Ujian & Libur)', description: 'Menghentikan total seluruh aktivitas produksi fisik selama 2 minggu Ujian PAS/SAS dan 1 minggu libur semester.', daysFromNow: 30, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pimpro-4', title: 'Konsolidasi Ulang & Aktifkan Peran Cadangan', description: 'Memimpin konsolidasi ulang pasca-libur & mengaktifkan prosedur peran cadangan.', daysFromNow: 30, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sekre-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sekre-2', title: 'Rekap Presensi Harian & Izin Les', description: 'Mengelola rekapitulasi presensi harian dan data izin les akademik di web.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sekre-3', title: 'Bekukan Lalu Lintas Surat (Ujian & Libur)', description: 'Membekukan seluruh lalu lintas surat dan pengumuman grup selama 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sekre-4', title: 'Koordinasi Cetakan Tiket, Nametag, Buku Acara', description: 'Berkoordinasi dengan Divisi Dokpub untuk cetakan fisik tiket, nametag panitia, dan buku acara.', daysFromNow: 20, priority: 'MEDIUM', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Pelaksanaan' },
  { id: 'tp-pelaksanaan-bend-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-bend-2', title: 'Kelola Arus Kas Harian via Web', description: 'Mengelola arus kas harian via web agar tidak menyita waktu belajar dan jadwal les.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-bend-3', title: 'Stop Transaksi & Penagihan (Ujian & Libur)', description: 'Menghentikan aktivitas transaksi, penagihan kas, dan belanja fisik selama 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sut-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sut-2', title: 'Pimpin Latihan 2x/Minggu, 1 Jam', description: 'Memimpin latihan maks 2x/minggu sebelum H-14, durasi maks 1 jam/pertemuan.', daysFromNow: 14, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sut-3', title: 'Henti Latihan Fisik (Ujian & Libur)', description: 'Menerapkan Henti Latihan Fisik Total selama 2 minggu Ujian dan 1 minggu libur.', daysFromNow: 30, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-sut-4', title: 'Pimpin Gladi Bersih Pasca-Libur', description: 'Memimpin gladi bersih utuh pada minggu pertama setelah masuk pasca-libur.', daysFromNow: 32, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Pelaksanaan' },
  { id: 'tp-pelaksanaan-astrada-1', title: 'Pandu Pemanasan & Briefing (Maks 1 Jam)', description: 'Memandu pemanasan dan briefing singkat dalam total maks 1 jam per pertemuan.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Pelaksanaan' },
  { id: 'tp-pelaksanaan-astrada-2', title: 'Kelola Setor Hafalan via Audio/Video Web', description: 'Mengelola penyerahan setor hafalan dialog via rekaman audio/video di web.', daysFromNow: 14, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Pelaksanaan' },
  { id: 'tp-pelaksanaan-astrada-3', title: 'Latih Shadow Player (Pemeran Cadangan)', description: 'Melatih Shadow Player agar siap menggantikan pemain utama jika bentrok jadwal les.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Pelaksanaan' },
  { id: 'tp-pelaksanaan-astrada-4', title: 'Kosongkan Jadwal (Ujian & Libur)', description: 'Mengosongkan seluruh jadwal latihan dan koordinasi selama 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pemain-1', title: 'Ikut Pemanasan & Briefing (Maks 1 Jam)', description: 'Wajib mengikuti pemanasan & briefing di awal latihan (maks 1 jam/pertemuan, maks 2x/minggu sebelum H-14).', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pemain-2', title: 'Setor Hafalan Dialog via Video Asinkron', description: 'Menyetorkan hafalan dialog via rekaman video ke web secara asinkron dari rumah.', daysFromNow: 14, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pemain-3', title: 'Hadiri Latihan Fisik Modular & Shadow', description: 'Menghadiri latihan fisik modular sesuai adegan dan berkoordinasi dengan Shadow Player.', daysFromNow: 14, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Pelaksanaan' },
  { id: 'tp-pelaksanaan-pemain-4', title: 'Bebas Latihan Fisik (Ujian & Libur)', description: 'Bebas dari kegiatan latihan fisik selama 2 minggu Ujian dan 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Pelaksanaan' },
];

const PERTUNJUKAN: TaskTemplate[] = [
  { id: 'tp-pertunjukan-pimpro-1', title: 'Rapat Komando Akhir & Alokasi 45 Menit', description: 'Memimpin rapat komando akhir, koordinasi pengelola tempat untuk 45 menit (10 persiapan, 30 tampil, 5 bongkar).', daysFromNow: 2, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Show Time' },
  { id: 'tp-pertunjukan-pimpro-2', title: 'Kontrol Sterilisasi Panggung & Penilaian', description: 'Mengontrol sterilisasi panggung bersama Stage Crew & memimpin penilaian berjenjang via borang evaluasi web.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Show Time' },
  { id: 'tp-pertunjukan-sekre-1', title: 'Zonasi Meja Tamu & Validasi Tiket', description: 'Berkoordinasi untuk zonasi meja penerimaan tamu dan validasi tiket digital berbasis web.', daysFromNow: 1, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Show Time' },
  { id: 'tp-pertunjukan-sekre-2', title: 'Sambut Tamu & Catat Statistik Penonton', description: 'Menyambut tamu undangan, kontrol pemindaian tiket digital, dan catat statistik kehadiran riil penonton.', daysFromNow: 1, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Show Time' },
  { id: 'tp-pertunjukan-bend-1', title: 'Koordinasi Logistik & Dana Darurat', description: 'Berkoordinasi dengan logistik untuk pembagian ruang penyimpanan dan penyediaan dana darurat bersama.', daysFromNow: 1, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Show Time' },
  { id: 'tp-pertunjukan-bend-2', title: 'Alokasi Dana P3K & Konsumsi Tim', description: 'Mengalokasikan dana darurat P3K & teknis cepat, berkoordinasi dengan Divisi Konsumsi.', daysFromNow: 1, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Show Time' },
  { id: 'tp-pertunjukan-sut-1', title: 'Koordinasi Stage Manager — Durasi 30 Menit', description: 'Berkoordinasi ketat dengan Stage Manager agar durasi pertunjukan tepat 30 menit.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Show Time' },
  { id: 'tp-pertunjukan-sut-2', title: 'Motivasi Akhir & Input Nilai Keaktoran', description: 'Memberikan motivasi akhir, memantau kestabilan emosi pemain, dan input nilai keaktoran di web.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Show Time' },
  { id: 'tp-pertunjukan-astrada-1', title: 'Alur Pemanggilan Pemain ke Wing', description: 'Berkoordinasi dengan Floor Manager untuk alur pemanggilan pemain ke area wing panggung.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Show Time' },
  { id: 'tp-pertunjukan-astrada-2', title: 'Pemanasan Vokal & Kontrol Urutan 30 Menit', description: 'Memandu pemanasan vokal singkat, kontrol urutan adegan sesuai 30 menit, siap gantikan Sutradara jika berhalangan.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Show Time' },
  { id: 'tp-pertunjukan-pemain-1', title: 'Pemanasan Vokal Fisik & Siap di Wing', description: 'Wajib pemanasan vokal & fisik, jaga ketenangan ruang tunggu, siap di wing tepat waktu.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Show Time' },
  { id: 'tp-pertunjukan-pemain-2', title: 'Tampil 30 Menit & Isi Penilaian Rekan', description: 'Tampil maksimal 30 menit dan isi lembar penilaian berjenjang antarteman via web.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Show Time' },
];

const PASCA: TaskTemplate[] = [
  { id: 'tp-pasca-pimpro-1', title: 'Pembersihan Total Panggung', description: 'Mengoordinasikan pembersihan total panggung dan mengembalikan area kepada pengelola tempat.', daysFromNow: 3, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pasca-Produksi' },
  { id: 'tp-pasca-pimpro-2', title: 'Forum Apresiasi & LPJ Komprehensif', description: 'Memimpin forum apresiasi resmi dan menyusun LPJ Produksi komprehensif berbasis data web.', daysFromNow: 7, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Pimpinan Produksi', reference: 'Job Desc Pimpro § Pasca-Produksi' },
  { id: 'tp-pasca-sekre-1', title: 'Kompilasi Dokumen ke Arsip Web', description: 'Mengompilasi dokumen produksi, laporan presensi, dan data penonton ke direktori arsip web.', daysFromNow: 5, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sekretaris', reference: 'Job Desc Sekretaris § Pasca-Produksi' },
  { id: 'tp-pasca-bend-1', title: 'Rekap Nota, LPJ Keuangan & Transparansi', description: 'Rekap nota digital, susun LPJ Keuangan Akhir, hitung sisa kas, paparkan transparansi ke semua.', daysFromNow: 7, priority: 'CRITICAL', targetType: 'PERAN', targetRole: 'Bendahara', reference: 'Job Desc Bendahara § Pasca-Produksi' },
  { id: 'tp-pasca-sut-1', title: 'Analisis Keaktoran Individual via Web', description: 'Sampaikan analisis keaktoran individual via web & konsolidasi catatan akhir penyutradaraan.', daysFromNow: 5, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Sutradara', reference: 'Job Desc Sutradara § Pasca-Produksi' },
  { id: 'tp-pasca-astrada-1', title: 'Konsolidasi Catatan Pemain ke Arsip Web', description: 'Konsolidasi seluruh catatan harian pemain & unggah ke arsip evaluasi web.', daysFromNow: 5, priority: 'MEDIUM', targetType: 'PERAN', targetRole: 'Asisten Sutradara', reference: 'Job Desc Astrada § Pasca-Produksi' },
  { id: 'tp-pasca-pemain-1', title: 'Bersihkan Rias & Refleksi Kritis', description: 'Bersihkan rias, rapikan kostum pribadi, dan isi lembar refleksi kritis keaktoran di web.', daysFromNow: 3, priority: 'HIGH', targetType: 'PERAN', targetRole: 'Pemain', reference: 'Job Desc Pemain § Pasca-Produksi' },
];

// =====================================================
// BAGIAN 2: 6 DIVISI
// =====================================================

const DIVISI_PERSIAPAN: TaskTemplate[] = [
  { id: 'tp-persiapan-kostum-1', title: 'Moodboard Kostum (boleh pakai AI)', description: 'Mengembangkan moodboard kostum memanfaatkan AI, mengunggah rancangan visual ke web.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Perencanaan' },
  { id: 'tp-persiapan-kostum-2', title: 'Data Ukuran Tubuh Pemain', description: 'Mendata ukuran tubuh pemain dari data mandiri di web.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Perencanaan' },
  { id: 'tp-persiapan-rias-1', title: 'Face Chart Berbasis Analisis Karakter', description: 'Membuat face chart berbasis analisis karakter menggunakan AI, upload ke web.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Perencanaan' },
  { id: 'tp-persiapan-rias-2', title: 'Data Kit Rias Pribadi Higienis', description: 'Mendata kit rias pribadi yang higienis.', daysFromNow: 10, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Perencanaan' },
  { id: 'tp-persiapan-rias-3', title: 'Alur Jadwal Urutan Merias', description: 'Menyusun alur jadwal urutan merias yang ringkas agar tidak menguras stamina pemain.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Perencanaan' },
  { id: 'tp-persiapan-properti-1', title: 'Breakdown Properti per Adegan', description: 'Menyusun breakdown daftar properti per adegan dengan prioritas daur ulang.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Perencanaan' },
  { id: 'tp-persiapan-properti-2', title: 'Denah Penataan Properti di Wing', description: 'Merancang denah penataan properti di wing panggung bersama Stage Crew.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Perencanaan' },
  { id: 'tp-persiapan-panggung-1', title: 'Sketsa Denah Panggung 2D per Adegan', description: 'Merancang sketsa denah panggung 2D per adegan, upload ke web.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Perencanaan' },
  { id: 'tp-persiapan-panggung-2', title: 'Peta Alur Keluar Masuk Dekorasi', description: 'Memetakan alur keluar masuk dekorasi panggung.', daysFromNow: 10, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Perencanaan' },
  { id: 'tp-persiapan-panggung-3', title: 'Sistem Cross-Operator (Kru Cadangan)', description: 'Menyusun sistem Cross-Operator agar tugas panggung tetap berjalan jika ada anggota yang les.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Perencanaan' },
  { id: 'tp-persiapan-dokpub-1', title: 'Strategi Publikasi & Kalender Konten', description: 'Menyusun strategi publikasi digital, kalender konten, dan materi promosi di waktu senggang.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Perencanaan' },
  { id: 'tp-persiapan-musik-1', title: 'Inventarisasi Alat Musik', description: 'Menginventarisasi alat musik dan upload ke web.', daysFromNow: 10, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Perencanaan' },
  { id: 'tp-persiapan-musik-2', title: 'Sound Cue Sheet ke Web', description: 'Mengunggah sound cue sheet ke platform web.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Perencanaan' },
  { id: 'tp-persiapan-musik-3', title: 'Tata Letak Mikrofon Panggung', description: 'Merancang tata letak mikrofon panggung bersama Stage Crew.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Perencanaan' },
  { id: 'tp-persiapan-musik-4', title: 'Skema Cross-Operator Penataan Suara', description: 'Menerapkan skema Cross-Operator agar latihan tidak terganggu jika penata musik sedang les.', daysFromNow: 10, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Perencanaan' },
];

const DIVISI_PELAKSANAAN: TaskTemplate[] = [
  { id: 'tp-pelaksanaan-kostum-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Pelaksanaan' },
  { id: 'tp-pelaksanaan-kostum-2', title: 'Fitting Bergantian & Modifikasi Pakaian Bekas', description: 'Fitting kostum bergantian (maks 1 jam/sesi), modifikasi pakaian bekas.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Pelaksanaan' },
  { id: 'tp-pelaksanaan-kostum-3', title: 'Latih Simulasi Quick Change', description: 'Melatih simulasi quick change (ganti baju cepat).', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Pelaksanaan' },
  { id: 'tp-pelaksanaan-kostum-4', title: 'Kunci & Simpan Aset Kostum (Ujian & Libur)', description: 'Menghentikan pengerjaan kostum & kunci aset dengan aman sebelum 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Pelaksanaan' },
  { id: 'tp-pelaksanaan-rias-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Pelaksanaan' },
  { id: 'tp-pelaksanaan-rias-2', title: 'Latih Aplikasi Rias Pemain & Shadow Player', description: 'Latih aplikasi rias pada pemain dan Shadow Player (maks 1 jam/sesi termasuk briefing).', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Pelaksanaan' },
  { id: 'tp-pelaksanaan-rias-3', title: 'Sterilkan & Amankan Alat Rias (Ujian & Libur)', description: 'Sterilkan, kemas, dan amankan seluruh peralatan rias sebelum 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Pelaksanaan' },
  { id: 'tp-pelaksanaan-properti-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Pelaksanaan' },
  { id: 'tp-pelaksanaan-properti-2', title: 'Rakit Properti Sederhana (Maks 1 Jam)', description: 'Merakit properti sederhana pada jam resmi (maks 1 jam/pertemuan), susun tata letak.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Pelaksanaan' },
  { id: 'tp-pelaksanaan-properti-3', title: 'Sediakan Air Galon saat Latihan', description: 'Menyediakan pasokan air galon saat latihan berlangsung.', daysFromNow: 14, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Pelaksanaan' },
  { id: 'tp-pelaksanaan-properti-4', title: 'Simpan Properti di Gudang (Ujian & Libur)', description: 'Simpan properti di gudang terkunci sebelum 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Pelaksanaan' },
  { id: 'tp-pelaksanaan-panggung-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pelaksanaan' },
  { id: 'tp-pelaksanaan-panggung-2', title: 'Pasang Lakban Spotting Posisi', description: 'Memasang lakban penanda spotting posisi pemain di panggung.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pelaksanaan' },
  { id: 'tp-pelaksanaan-panggung-3', title: 'Konstruksi Set Panggung Sederhana', description: 'Mengonstruksi set panggung sederhana sesuai desain.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pelaksanaan' },
  { id: 'tp-pelaksanaan-panggung-4', title: 'Simulasi Pemindahan Set (Maks 1 Jam)', description: 'Simulasi pemindahan set panggung maks 1 jam/sesi termasuk rapat.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pelaksanaan' },
  { id: 'tp-pelaksanaan-panggung-5', title: 'Amankan Set Dekorasi (Ujian & Libur)', description: 'Stop aktivitas panggung & amankan set dekorasi sebelum 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pelaksanaan' },
  { id: 'tp-pelaksanaan-dokpub-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Pelaksanaan' },
  { id: 'tp-pelaksanaan-dokpub-2', title: 'Dokumentasi BTS dalam Durasi Latihan', description: 'Dokumentasi proses BTS ringkas dalam durasi latihan maks 1 jam/pertemuan.', daysFromNow: 14, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Pelaksanaan' },
  { id: 'tp-pelaksanaan-dokpub-3', title: 'Unggah Video Latihan ke Web', description: 'Upload rekaman video latihan ke web agar Sutradara & pemain dapat evaluasi asinkron.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Pelaksanaan' },
  { id: 'tp-pelaksanaan-dokpub-4', title: 'Scheduled Posting Promosi (Libur)', description: 'Aktifkan fitur scheduled posting untuk promosi ringan selama 1 minggu libur semester.', daysFromNow: 30, priority: 'MEDIUM', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Pelaksanaan' },
  { id: 'tp-pelaksanaan-musik-1', title: 'Ikut Pemanasan Bersama Tim', description: 'Disarankan mengikuti pemanasan bersama tim.', daysFromNow: 14, priority: 'LOW', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Pelaksanaan' },
  { id: 'tp-pelaksanaan-musik-2', title: 'Unggah Draf Rekaman Musik Iringan', description: 'Upload draf rekaman musik ke web agar pemain bisa latihan hafalan dari rumah.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Pelaksanaan' },
  { id: 'tp-pelaksanaan-musik-3', title: 'Latihan Musik Efisien (Maks 1 Jam)', description: 'Latihan musik efisien maks 1 jam/pertemuan termasuk rapat penyelarasan adegan.', daysFromNow: 14, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Pelaksanaan' },
  { id: 'tp-pelaksanaan-musik-4', title: 'Kunci Alat Musik (Ujian & Libur)', description: 'Selesaikan penyelarasan musik & kunci semua instrumen sebelum 2 minggu Ujian + 1 minggu libur.', daysFromNow: 30, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Pelaksanaan' },
];

const DIVISI_PERTUNJUKAN: TaskTemplate[] = [
  { id: 'tp-pertunjukan-kostum-1', title: 'Bagi Area Rak Gantung di Balik Panggung', description: 'Koordinasi dengan penata busana kerabat kerja untuk pembagian area rak gantung baju.', daysFromNow: 1, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Show Time' },
  { id: 'tp-pertunjukan-kostum-2', title: 'Tata Area Ganti & Dampingi Quick Change', description: 'Tata area ganti sesuai urutan adegan & dampingi proses quick change pemain.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Show Time' },
  { id: 'tp-pertunjukan-rias-1', title: 'Koordinasi Area Cermin & Listrik', description: 'Koordinasi dengan tim rias kerabat kerja untuk berbagi area cermin dan stopkontak.', daysFromNow: 1, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Show Time' },
  { id: 'tp-pertunjukan-rias-2', title: 'Eksekusi Tata Rias Sesuai Timeline & Touch-Up', description: 'Eksekusi rias sesuai timeline & standby touch-up cepat di antara adegan.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Show Time' },
  { id: 'tp-pertunjukan-properti-1', title: 'Bagi Zona Prop Table di Wing', description: 'Koordinasi dengan logistik untuk pembagian zona prop table agar tidak tertukar.', daysFromNow: 1, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Show Time' },
  { id: 'tp-pertunjukan-properti-2', title: 'Tata & Pindah Properti Cepat', description: 'Tata properti 10 menit persiapan & eksekusi transisi cepat selama 30 menit pertunjukan.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Show Time' },
  { id: 'tp-pertunjukan-panggung-1', title: 'Pasang Set 10 Menit & Bongkar 5 Menit', description: 'Eksekusi pasang set 10 menit & bongkar cepat 5 menit terakhir.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Show Time' },
  { id: 'tp-pertunjukan-panggung-2', title: 'Jaga Sterilitas & Pindah Dekorasi Tanpa Suara', description: 'Jaga sterilitas area samping & pindahkan dekorasi cepat tanpa suara selama 30 menit.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Show Time' },
  { id: 'tp-pertunjukan-dokpub-1', title: 'Posisi Tripod & Sudut Kamera', description: 'Koordinasi dengan tim dokumentasi untuk pembagian posisi tripod & sudut kamera.', daysFromNow: 1, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Show Time' },
  { id: 'tp-pertunjukan-dokpub-2', title: 'Rekam Pementasan 30 Menit & Foto Momen', description: 'Rekam pementasan utuh 30 menit dengan audio jernih & foto momen panggung.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Show Time' },
  { id: 'tp-pertunjukan-musik-1', title: 'Bagi Channel Mixer & Mikrofon', description: 'Koordinasi dengan sound engineer untuk pembagian channel mixer & penggunaan mikrofon.', daysFromNow: 1, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Show Time' },
  { id: 'tp-pertunjukan-musik-2', title: 'Check Sound 10 Menit & Musik Presisi', description: 'Check sound 10 menit & mainkan musik iringan presisi mengikuti alur 30 menit.', daysFromNow: 1, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Show Time' },
];

const DIVISI_PASCA: TaskTemplate[] = [
  { id: 'tp-pasca-kostum-1', title: 'Cuci, Bersihkan & Kembalikan Aset Kostum', description: 'Bersihkan, cuci, kembalikan aset kostum pinjaman & input data inventaris akhir ke web.', daysFromNow: 5, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Busana', reference: 'Job Desc Kostum § Pasca-Produksi' },
  { id: 'tp-pasca-rias-1', title: 'Bersihkan Rias & Sterilkan Alat', description: 'Dampingi pembersihan make-up remover, sterilkan alat, upload laporan kerja ke web.', daysFromNow: 3, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Rias', reference: 'Job Desc Rias § Pasca-Produksi' },
  { id: 'tp-pasca-properti-1', title: 'Bersihkan Backstage & Kembalikan Inventaris', description: 'Bersihkan area backstage, kembalikan inventaris sekolah, update status barang di web.', daysFromNow: 3, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Perlengkapan', reference: 'Job Desc Properti § Pasca-Produksi' },
  { id: 'tp-pasca-panggung-1', title: 'Bongkar Set & Kembalikan Panggung', description: 'Bongkar set dekorasi aman, kembalikan panggung seperti semula, isi borang penilaian web.', daysFromNow: 3, priority: 'CRITICAL', targetType: 'DIVISI', targetDivision: 'Tata Panggung', reference: 'Job Desc Panggung § Pasca-Produksi' },
  { id: 'tp-pasca-dokpub-1', title: 'Sunting Aftermovie & Upload ke Web', description: 'Sunting video aftermovie sinematik, organisir file foto/video ke repositori web.', daysFromNow: 7, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Publikasi & Dokumentasi', reference: 'Job Desc Dokpub § Pasca-Produksi' },
  { id: 'tp-pasca-musik-1', title: 'Rapikan Instrumen & Laporan Teknis Suara', description: 'Rapikan, bersihkan, kembalikan instrumen ke penyimpanan & isi laporan teknis suara di web.', daysFromNow: 5, priority: 'HIGH', targetType: 'DIVISI', targetDivision: 'Tata Musik & Suara', reference: 'Job Desc Musik § Pasca-Produksi' },
];

// =====================================================
// GABUNGAN FINAL
// =====================================================
export const TASK_TEMPLATES: Record<ProductionStage, TaskTemplate[]> = {
  PERSIAPAN: [...PERSIAPAN, ...DIVISI_PERSIAPAN],
  PELAKSANAAN: [...PELAKSANAAN, ...DIVISI_PELAKSANAAN],
  PERTUNJUKAN: [...PERTUNJUKAN, ...DIVISI_PERTUNJUKAN],
  PASCA: [...PASCA, ...DIVISI_PASCA],
};

export const STAGE_INFO_TASK = {
  PERSIAPAN: { label: 'Tahap 1 — Persiapan', gradient: 'from-amber-600 to-amber-800', desc: 'Riset, naskah, desain, RAB, Master Schedule' },
  PELAKSANAAN: { label: 'Tahap 2 — Pelaksanaan', gradient: 'from-blue-600 to-blue-800', desc: 'Latihan rutin, produksi properti & kostum, dokumentasi' },
  PERTUNJUKAN: { label: 'Tahap 3 — Pertunjukan', gradient: 'from-purple-600 to-purple-800', desc: 'Gladi bersih, pementasan utama, standby' },
  PASCA: { label: 'Tahap 4 — Pasca Produksi', gradient: 'from-emerald-600 to-emerald-800', desc: 'Evaluasi, LPJ, pengembalian aset, aftermovie' },
};
