import { ProductionStage, DivisionType, UserRole } from './types';

export interface TaskTemplate {
  id: string;
  title: string;
  description: string;
  daysFromNow: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  targetType: 'SEMUA' | 'DIVISI' | 'PERAN';
  targetDivision?: DivisionType;
  targetRole?: UserRole;
  reference: string;
}

export const TASK_TEMPLATES: Record<ProductionStage, TaskTemplate[]> = {
  // =========================================
  // TAHAP 1: PERSIAPAN
  // =========================================
  PERSIAPAN: [
    {
      id: 'tp-persiapan-1',
      title: 'Master Production Schedule',
      description: 'Menyusun Master Production Schedule di web + pengesahan Guru Pembimbing & Kepala Sekolah. Menetapkan pekan bebas ujian PAS/SAS dan libur semester.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-2',
      title: 'Tata Kelola Administrasi Web & Formulir Izin Les',
      description: 'Mengelola administrasi berbasis web, buat formulir izin les akademik/bimbel otomatis, dan unggah draf naskah cetak ke repositori web.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-3',
      title: 'RAB & Sistem Digitalisasi Nota Kas',
      description: 'Menyusun Anggaran Pendapatan & Belanja via web, tetapkan kebijakan material daur ulang, atur sistem nota kas digital yang real-time.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-4',
      title: 'Visi Penyutradaraan & Scene Breakdown',
      description: 'Menyusun sistem latihan modular berbasis Scene Breakdown dan mengunggah Visi Penyutradaraan ke web.',
      daysFromNow: 7,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-5',
      title: 'Call Sheet & Upload Prompt Book',
      description: 'Menyusun Call Sheet latihan per adegan selaras jadwal les, dan mengunggah prompt book berisi instruksi cueing.',
      daysFromNow: 8,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-6',
      title: 'Analisis Karakter & Jadwal Les Pribadi',
      description: 'Pemain mendalami tokoh, susun lembar analisis karakter di web, dan serahkan jadwal les pribadi melalui sistem.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-7',
      title: 'Moodboard Kostum & Data Ukuran Pemain',
      description: 'Kembangkan moodboard kostum (boleh pakai AI), upload ke web, dan data ukuran tubuh pemain.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-8',
      title: 'Face Chart & Jadwal Urutan Rias',
      description: 'Buat face chart analisis karakter (boleh pakai AI), upload ke web, susun jadwal urutan rias yang ringkas.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-9',
      title: 'Breakdown Properti & Denah Wing',
      description: 'Susun breakdown properti per adegan (prioritaskan daur ulang) dan rancang denah properti di wing bersama Stage Crew.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-10',
      title: 'Sketsa Denah Panggung & Cross-Operator',
      description: 'Rancang sketsa denah panggung 2D per adegan, upload ke web, dan susun sistem Cross-Operator (kru cadangan).',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-11',
      title: 'Strategi Publikasi & Kalender Konten',
      description: 'Susun strategi publikasi digital, rancang kalender konten, buat materi promosi di waktu senggang.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Perencanaan Pra-Produksi',
    },
    {
      id: 'tp-persiapan-12',
      title: 'Sound Cue Sheet & Tata Letak Mic',
      description: 'Inventarisasi alat musik, upload sound cue sheet, rancang tata letak mic bersama Stage Crew, terapkan Cross-Operator.',
      daysFromNow: 10,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Perencanaan Pra-Produksi',
    },
  ],

  // =========================================
  // TAHAP 2: PELAKSANAAN
  // =========================================
  PELAKSANAAN: [
    {
      id: 'tp-pelaksanaan-1',
      title: 'Briefing & Latihan Rutin (Maks 2x/Minggu, 1 Jam)',
      description: 'Pemanasan + briefing singkat + latihan maks 1 jam. Maks 2x/minggu sebelum H-14. Dilarang latihan di akhir pekan.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'SEMUA',
      reference: 'Job Desc Semua § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-2',
      title: 'Rekap Presensi Harian & Data Izin Les',
      description: 'Sekretaris mengelola rekapitulasi presensi harian dan data izin les akademik di sistem web.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-3',
      title: 'Arus Kas Harian via Web',
      description: 'Bendahara mengelola arus kas harian via web agar tidak menyita waktu belajar dan jadwal les.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-4',
      title: 'Setor Hafalan Dialog Video Asinkron',
      description: 'Pemain setor hafalan dialog via rekaman video ke web secara asinkron dari rumah tanpa ganggu belajar & les.',
      daysFromNow: 14,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-5',
      title: 'Kelola Setor Hafalan & Latih Shadow Player',
      description: 'Asisten Sutradara kelola setoran hafalan via audio/video, latih Shadow Player (pemeran cadangan) agar siap gantikan pemain utama.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-6',
      title: 'Fitting Kostum & Simulasi Quick Change',
      description: 'Fitting bergantian (maks 1 jam/sesi), modifikasi pakaian bekas, latih simulasi quick change.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-7',
      title: 'Latihan Rias Pemain & Shadow Player',
      description: 'Latih aplikasi rias pada pemain & Shadow Player (maks 1 jam/sesi termasuk briefing).',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-8',
      title: 'Merakit Properti di Sekolah (Maks 1 Jam/Sesi)',
      description: 'Rakit properti sederhana pada jam resmi (maks 1 jam/pertemuan), susun tata letak, sediakan air galon.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-9',
      title: 'Lakban Spotting & Konstruksi Set Panggung',
      description: 'Pasang lakban spotting posisi pemain, konstruksi set panggung, simulasi pemindahan set (maks 1 jam/sesi).',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-10',
      title: 'Dokumentasi BTS & Upload Video Latihan',
      description: 'Dokumentasi BTS, upload video latihan ke web untuk evaluasi asinkron, aktifkan scheduled posting selama libur.',
      daysFromNow: 14,
      priority: 'MEDIUM',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-11',
      title: 'Upload Draf Rekaman Musik Iringan',
      description: 'Upload draf rekaman musik ke web agar pemain bisa latihan hafalan dari rumah mandiri.',
      daysFromNow: 14,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Pelaksanaan Produksi',
    },
    {
      id: 'tp-pelaksanaan-12',
      title: 'Henti Total Aktivitas Fisik (Pekan Ujian & Libur)',
      description: 'SEMUA WAJIB stop aktivitas fisik di sekolah selama 2 minggu ujian PAS/SAS dan 1 minggu libur. Aset dikunci.',
      daysFromNow: 30,
      priority: 'CRITICAL',
      targetType: 'SEMUA',
      reference: 'Job Desc Semua Peran § Pelaksanaan Produksi',
    },
  ],

  // =========================================
  // TAHAP 3: PERTUNJUKAN
  // =========================================
  PERTUNJUKAN: [
    {
      id: 'tp-pertunjukan-1',
      title: 'Rapat Komando Akhir & Alokasi 45 Menit',
      description: 'Pimpro pimpin rapat komando akhir, koordinasi pengelola tempat untuk 45 menit: 10 persiapan + 30 tampil + 5 bongkar.',
      daysFromNow: 2,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-2',
      title: 'Registrasi Tamu & Validasi Tiket Digital',
      description: 'Sekretaris atur zonasi meja penerimaan tamu, validasi tiket digital, catat statistik kehadiran penonton.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-3',
      title: 'Dana Darurat P3K & Konsumsi Tim',
      description: 'Bendahara alokasikan dana darurat P3K & teknis cepat, koordinasi dengan Divisi Konsumsi untuk pasokan makanan.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-4',
      title: 'Gladi Bersih Utuh & Instruksi 30 Menit',
      description: 'Sutradara pimpin gladi bersih pasca-libur, koordinasi Stage Manager agar durasi tepat 30 menit.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-5',
      title: 'Panggil Pemain dari Ruang Tunggu ke Wing',
      description: 'Astrada koordinasi Floor Manager, pimpin pemanasan vokal singkat, kontrol urutan adegan sesuai 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-6',
      title: 'Pemanasan Vokal Fisik & Standby di Wing',
      description: 'Pemain WAJIB pemanasan vokal fisik, jaga ketenangan, siap di wing tepat waktu. Tampil maksimal 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-7',
      title: 'Penataan Area Ganti & Quick Change',
      description: 'Kostum atur area rak gantung, tata area ganti sesuai urutan adegan, dampingi quick change pemain.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-8',
      title: 'Tata Rias Sesuai Timeline & Touch-Up Cepat',
      description: 'Rias bagi area cermin & listrik, eksekusi rias sesuai timeline, standby touch-up cepat antar adegan.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-9',
      title: 'Prop Table & Transisi Properti Cepat',
      description: 'Properti atur zona prop table wing, tata properti 10 menit persiapan, eksekusi transisi cepat 30 menit.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-10',
      title: 'Pasang Set 10 Menit & Bongkar Set 5 Menit',
      description: 'Panggung eksekusi pasang set 10 menit, bongkar cepat 5 menit terakhir. Jaga sterilitas area samping.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-11',
      title: 'Rekam Pementasan Utuh 30 Menit',
      description: 'Dokpub atur posisi tripod & sudut kamera, rekam pementasan utuh 30 menit audio jernih, foto momen panggung.',
      daysFromNow: 1,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Pertunjukan Show Time',
    },
    {
      id: 'tp-pertunjukan-12',
      title: 'Check Sound 10 Menit & Musik Presisi',
      description: 'Musik atur channel mixer, check sound 10 menit, mainkan musik iringan presisi mengikuti alur 30 menit.',
      daysFromNow: 1,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Pertunjukan Show Time',
    },
  ],

  // =========================================
  // TAHAP 4: PASCA
  // =========================================
  PASCA: [
    {
      id: 'tp-pasca-1',
      title: 'Pembersihan Total & Forum Apresiasi',
      description: 'Pimpro koordinasi pembersihan total panggung, kembalikan area ke pengelola, pimpin forum apresiasi resmi.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Pimpinan Produksi',
      reference: 'Job Desc Pimpro § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-2',
      title: 'Kompilasi Dokumen & Data Penonton',
      description: 'Sekretaris kompilasi dokumen produksi, laporan presensi, dan data penonton ke direktori arsip web.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sekretaris',
      reference: 'Job Desc Sekretaris § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-3',
      title: 'Rekap Nota & Laporan Keuangan Akhir',
      description: 'Bendahara rekap nota digital, susun Laporan Keuangan Akhir, hitung sisa kas, paparkan transparansi.',
      daysFromNow: 5,
      priority: 'CRITICAL',
      targetType: 'PERAN',
      targetRole: 'Bendahara',
      reference: 'Job Desc Bendahara § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-4',
      title: 'Analisis Perkembangan Keaktoran Individual',
      description: 'Sutradara sampaikan analisis keaktoran individual via web, konsolidasi catatan akhir penyutradaraan.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Sutradara',
      reference: 'Job Desc Sutradara § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-5',
      title: 'Konsolidasi Catatan Perkembangan Pemain',
      description: 'Astrada konsolidasi catatan harian pemain, upload ke arsip evaluasi web.',
      daysFromNow: 5,
      priority: 'MEDIUM',
      targetType: 'PERAN',
      targetRole: 'Asisten Sutradara',
      reference: 'Job Desc Astrada § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-6',
      title: 'Refleksi Kritis Keaktoran & Bersihkan Rias',
      description: 'Pemain bersihkan rias, rapikan kostum, isi lembar refleksi kritis keaktoran di web.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'PERAN',
      targetRole: 'Pemain',
      reference: 'Job Desc Pemain § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-7',
      title: 'Cuci & Kembalikan Aset Kostum',
      description: 'Kostum bersihkan, cuci, kembalikan aset pinjaman, input data inventaris akhir ke web.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Busana',
      reference: 'Job Desc Kostum § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-8',
      title: 'Bersihkan Rias & Sterilkan Alat',
      description: 'Rias dampingi pembersihan make-up remover, sterilkan alat, upload laporan kerja ke web.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Rias',
      reference: 'Job Desc Rias § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-9',
      title: 'Kembalikan Inventaris & Update Status',
      description: 'Properti bersihkan area belakang panggung, kembalikan inventaris sekolah, update status barang.',
      daysFromNow: 3,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Perlengkapan',
      reference: 'Job Desc Properti § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-10',
      title: 'Bongkar Set & Kembalikan Panggung',
      description: 'Panggung bongkar set aman, kembalikan panggung seperti semula, isi borang penilaian berjenjang.',
      daysFromNow: 3,
      priority: 'CRITICAL',
      targetType: 'DIVISI',
      targetDivision: 'Tata Panggung',
      reference: 'Job Desc Panggung § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-11',
      title: 'Sunting Aftermovie & Upload',
      description: 'Dokpub sunting aftermovie sinematik, organisir file foto/video ke repositori web.',
      daysFromNow: 7,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Publikasi & Dokumentasi',
      reference: 'Job Desc Dokpub § Evaluasi Pasca-Produksi',
    },
    {
      id: 'tp-pasca-12',
      title: 'Rapikan Instrumen & Laporan Teknis Suara',
      description: 'Musik rapikan & kembalikan instrumen ke ruang penyimpanan, isi laporan evaluasi teknis suara.',
      daysFromNow: 5,
      priority: 'HIGH',
      targetType: 'DIVISI',
      targetDivision: 'Tata Musik & Suara',
      reference: 'Job Desc Musik § Evaluasi Pasca-Produksi',
    },
  ],
};

export const STAGE_INFO_TASK = {
  PERSIAPAN: { label: 'Tahap 1 — Persiapan', gradient: 'from-amber-600 to-amber-800', desc: 'Riset, naskah, desain, RAB, Master Schedule' },
  PELAKSANAAN: { label: 'Tahap 2 — Pelaksanaan', gradient: 'from-blue-600 to-blue-800', desc: 'Latihan rutin, produksi properti & kostum, dokumentasi' },
  PERTUNJUKAN: { label: 'Tahap 3 — Pertunjukan', gradient: 'from-purple-600 to-purple-800', desc: 'Gladi bersih, pementasan utama, standby' },
  PASCA: { label: 'Tahap 4 — Pasca Produksi', gradient: 'from-emerald-600 to-emerald-800', desc: 'Evaluasi, LPJ, pengembalian aset, aftermovie' },
};
